# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: ":shipit: Publish Release"
    plugins: [$CI_TOOLKIT_PLUGIN, $NVM_PLUGIN]
    command: |
      echo "--- :robot_face: Set up Git identity"
      git config user.name "Studio Release Bot"
      git config user.email "studio-bot@masonjames.com"

      .buildkite/commands/checkout-release-branch.sh "${RELEASE_VERSION}"

      echo "--- :ruby: Setup Ruby Tools"
      install_gems

      echo "--- :shipit: Publish Release"
      bundle exec fastlane publish_release version:"${RELEASE_VERSION}" github_username:"${GITHUB_USERNAME}" skip_confirm:true
    agents:
      queue: mac
    retry:
      manual:
        reason: Re-trigger this release action from the Release Dispatch workflow or the studio-release-dispatch Buildkite pipeline instead of retrying the individual job
        allowed: false
